version: '3.8'

services:
  # Main SoftwareHub Application
  softwarehub-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - EMAIL_SERVICE_URL=http://email-service:3001
      - CHAT_SERVICE_URL=http://chat-service:3002
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
    depends_on:
      - postgres
      - redis
      - email-service
      - chat-service
      - notification-service
    networks:
      - softwarehub-network

  # Email Service
  email-service:
    build: ./services/email-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    networks:
      - softwarehub-network

  # Chat Service
  chat-service:
    build: ./services/chat-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - CLIENT_URL=http://softwarehub-app:5000
      - REDIS_URL=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017/softwarehub-chat
    depends_on:
      - redis
      - mongo
    networks:
      - softwarehub-network

  # Notification Service
  notification-service:
    build: ./services/notification-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - FCM_SERVER_KEY=${FCM_SERVER_KEY}
    networks:
      - softwarehub-network

  # Worker Service
  worker-service:
    build: ./services/worker-service
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - EMAIL_SERVICE_URL=http://email-service:3001
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
    depends_on:
      - redis
      - email-service
      - notification-service
    networks:
      - softwarehub-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=softwarehub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - softwarehub-network

  # Redis for caching and message queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - softwarehub-network

  # MongoDB for chat history
  mongo:
    image: mongo:6
    environment:
      - MONGO_INITDB_DATABASE=softwarehub-chat
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - softwarehub-network

  # Nginx Load Balancer (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - softwarehub-app
    networks:
      - softwarehub-network

volumes:
  postgres_data:
  redis_data:
  mongo_data:

networks:
  softwarehub-network:
    driver: bridge